services:
  - type: web
    name: intelligent-field-assignment
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aiff-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: aiff-db
    databaseName: aiff_db
    user: aiff
